// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xlrsfyvydkrvcuykfgle.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhscnNmeXZ5ZGtydmN1eWtmZ2xlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2OTk3NDAsImV4cCI6MjA3NDI3NTc0MH0.Xntp3yhzRyBRXkAozC0edHJNZ4TsvxPQCWBdsKgCrJU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});